name: Rust

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: clean up
      run: find . -name \*.gcno -exec rm {} \;

    - name: Nightly toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true

    - name: Coverage test
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --all-features --no-fail-fast
      env:
        CARGO_INCREMENTAL: '0'
        RUSTFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Zno-landing-pads'

    - name: grcov
      uses: actions-rs/grcov@v0.1.5

    - name: Upload to codecov.io
      uses: codecov/codecov-action@v1.0.6
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        file: ${{ steps.grcov.outputs.report }} 


